<?php if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die(); ?>
<?php

use intec\core\collections\Arrays;
use intec\core\helpers\Html;
use intec\core\io\Path;

/**
 * @var Arrays $blocks
 * @var array $block
 * @var array $data
 * @var string $page
 * @var Path $path
 * @global CMain $APPLICATION
 */

?>

<?php $APPLICATION->IncludeComponent(
	"intec.universe:main.widget", 
	"products.4.custom", 
	array(
		"SETTINGS_USE" => "N",
		"LAZYLOAD_USE" => "Y",
		"IBLOCK_TYPE" => "1c_catalog",
		"IBLOCK_ID" => "43",
		"MODE" => "all",
		"ACTION" => "buy",
		"PRICE_CODE" => array(
			0 => "BASE",
			1 => "Оптовая цена",
			2 => "Рекламная цена",
		),
		"DISCOUNT_SHOW" => "Y",
		"SLIDER_USE" => "N",
		"TITLE_SHOW" => "N",
		"DESCRIPTION_SHOW" => "N",
		"COLUMNS" => "3",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"BASKET_URL" => "/personal/basket/",
		"CONSENT_URL" => "/company/consent/",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		"FORM_ID" => "6",
		"FORM_PROPERTY_PRODUCT" => "form_text_21",
		"FORM_REQUEST_ID" => "7",
		"FORM_REQUEST_PROPERTY_PRODUCT" => "form_text_25",
		"FORM_REQUEST_TEMPLATE" => ".default",
		"ORDER_FAST_USE" => "N",
		"DELAY_USE" => "N",
		"OFFERS_LIMIT" => "0",
		"QUICK_VIEW_USE" => "N",
		"QUICK_VIEW_DETAIL" => "N",
		"QUICK_VIEW_TEMPLATE" => "2",
		"QUICK_VIEW_LAZYLOAD_USE" => "Y",
		"QUICK_VIEW_PROPERTY_CODE" => array(
			0 => "PROPERTY_TYPE",
			1 => "PROPERTY_QUANTITY_OF_STRIPS",
			2 => "PROPERTY_POWER",
			3 => "PROPERTY_PROCREATOR",
			4 => "PROPERTY_SCOPE",
			5 => "PROPERTY_DISPLAY",
			6 => "PROPERTY_WEIGTH",
			7 => "PROPERTY_ENERGY_CONSUMPTION",
			8 => "PROPERTY_SETTINGS",
			9 => "PROPERTY_COMPOSITION",
			10 => "PROPERTY_LENGTH",
			11 => "PROPERTY_SEASON",
			12 => "PROPERTY_PATTERN",
			13 => "",
		),
		"QUICK_VIEW_PROPERTY_MARKS_HIT" => "HIT",
		"QUICK_VIEW_PROPERTY_MARKS_NEW" => "NEW",
		"QUICK_VIEW_PROPERTY_MARKS_RECOMMEND" => "RECOMMEND",
		"QUICK_VIEW_PROPERTY_PICTURES" => "PICTURES",
		"QUICK_VIEW_OFFERS_PROPERTY_PICTURES" => "PICTURES",
		"QUICK_VIEW_DELAY_USE" => "Y",
		"QUICK_VIEW_MARKS_SHOW" => "Y",
		"QUICK_VIEW_MARKS_ORIENTATION" => "horizontal",
		"QUICK_VIEW_GALLERY_PREVIEW" => "Y",
		"QUICK_VIEW_QUANTITY_SHOW" => "Y",
		"QUICK_VIEW_QUANTITY_MODE" => "number",
		"QUICK_VIEW_ACTION" => "buy",
		"QUICK_VIEW_COUNTER_SHOW" => "Y",
		"QUICK_VIEW_DESCRIPTION_SHOW" => "Y",
		"QUICK_VIEW_DESCRIPTION_MODE" => "preview",
		"QUICK_VIEW_PROPERTIES_SHOW" => "Y",
		"QUICK_VIEW_DETAIL_SHOW" => "Y",
		"PROPERTY_CATEGORY" => "CATEGORY",
		"PROPERTY_ORDER_USE" => "ORDER_USE",
		"PROPERTY_MARKS_HIT" => "HIT",
		"PROPERTY_MARKS_NEW" => "NEW",
		"PROPERTY_MARKS_RECOMMEND" => "RECOMMEND",
		"PROPERTY_PICTURES" => "MORE_PHOTO",
		"PROPERTY_STORES_SHOW" => "STORES_SHOW",
		"PROPERTY_ARTICLE" => "ARTICLE",
		"OFFERS_PROPERTY_PICTURES" => "MORE_PHOTO",
		"OFFERS_PROPERTY_STORES_SHOW" => "STORES_SHOW",
		"OFFERS_PROPERTY_ARTICLE" => "ARTICLE",
		"COMPARE_PATH" => "/catalog/compare.php",
		"COMPARE_NAME" => "compare",
		"SHOW_PRICE_COUNT" => "1",
		"TABS_ALIGN" => "left",
		"BLOCKS_HEADER_SHOW" => "Y",
		"BLOCKS_HEADER_TEXT" => "Популярные товары",
		"BORDERS" => "N",
		"BORDERS_STYLE" => "squared",
		"ARTICLE_SHOW" => "N",
		"MARKS_SHOW" => "Y",
		"NAME_POSITION" => "middle",
		"NAME_ALIGN" => "left",
		"PRICE_ALIGN" => "start",
		"IMAGE_SLIDER_SHOW" => "Y",
		"IMAGE_SLIDER_NAV_SHOW" => "N",
		"IMAGE_SLIDER_OVERLAY_USE" => "Y",
		"COUNTER_SHOW" => "N",
		"OFFERS_USE" => "Y",
		"OFFERS_ALIGN" => "left",
		"OFFERS_VIEW" => "default",
		"VOTE_SHOW" => "N",
		"VOTE_ALIGN" => "left",
		"VOTE_MODE" => "rating",
		"QUANTITY_SHOW" => "N",
		"QUANTITY_MODE" => "number",
		"QUANTITY_ALIGN" => "left",
		"USE_COMPARE" => "N",
		"CONVERT_CURRENCY" => "Y",
		"USE_PRICE_COUNT" => "N",
		"PRICE_VAT_INCLUDE" => "Y",
		"STORES_FIELDS" => array(
			0 => "ADDRESS",
			1 => "",
		),
		"BLOCKS_HEADER_ALIGN" => "left",
		"OFFERS_VARIABLE_SELECT" => "offer",
		"COMPONENT_TEMPLATE" => "products.4.custom",
		"ELEMENTS_COUNT" => "",
		"FORM_TEMPLATE" => ".default",
		"MEASURE_SHOW" => "N",
		"QUICK_VIEW_SLIDE_USE" => "N",
		"QUICK_VIEW_PROPERTY_ORDER_USE" => "",
		"QUICK_VIEW_PROPERTY_REQUEST_USE" => "",
		"QUICK_VIEW_OFFERS_VARIABLE_SELECT" => "",
		"QUICK_VIEW_ADDITIONAL_PRODUCTS" => "N",
		"QUICK_VIEW_COUNTER_MESSAGE_MAX_SHOW" => "Y",
		"QUICK_VIEW_TIMER_SHOW" => "N",
		"REGIONALITY_USE" => "N",
		"PROPERTY_REQUEST_USE" => "",
		"STORES_ID" => array(
			0 => "",
			1 => "",
		),
		"STORES_MIN_AMOUNT_USE" => "N",
		"STORES_GENERAL_INFORMATION" => "N",
		"OFFERS_PROPERTY_CODE" => array(
			0 => "TSVET",
			1 => "RAZMER",
			2 => "RAZMER_NANESENIYA",
			3 => "RAZMERY_UPAKOVKI_SM_T",
			4 => "CML2_BAR_CODE",
			5 => "ARTIKUL_POSTAVSHCHIKA",
			6 => "CML2_MANUFACTURER",
			7 => "FILES",
			8 => "MORE_PHOTO",
			9 => "CML2_TAXES",
			10 => "CML2_BASE_UNIT",
			11 => "CML2_TRAITS",
			12 => "CML2_ATTRIBUTES",
			13 => "CML2_ARTICLE",
			14 => "ARTIKUL",
			15 => "POSTAVSHCHIK",
			16 => "",
		),
		"BANNER_SHOW" => "N",
		"VIEW" => "sections",
		"COLUMNS_MOBILE" => "2",
		"LINES" => "",
		"BLOCKS_DESCRIPTION_SHOW" => "Y",
		"MARKS_ORIENTATION" => "horizontal",
		"IMAGE_ASPECT_RATIO" => "1:1",
		"RECALCULATION_PRICES_USE" => "N",
		"PRICE_DISCOUNT_PERCENT" => "N",
		"OFFERS_PROPERTY_PICTURE_DIRECTORY" => "",
		"SECTION_TIMER_SHOW" => "N",
		"PURCHASE_BASKET_BUTTON_TEXT" => "В корзину",
		"PURCHASE_ORDER_BUTTON_TEXT" => "Заказать",
		"PURCHASE_REQUEST_BUTTON_TEXT" => "Уточнить цену",
		"BLOCKS_FOOTER_SHOW" => "N",
		"LIST_URL" => "#SITE_DIR#catalog/",
		"BLOCKS_DESCRIPTION_TEXT" => "Подходит для продукции из натуральной, эко-кожи, дерева, бумаги, картона.",
		"BLOCKS_DESCRIPTION_ALIGN" => "left",
		"SECTIONS_TITLE_SHOW" => "N",
		"CURRENCY_ID" => "RUB"
	),
	false
);?>

