<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php") ?>
<?php

use Bitrix\Main\ModuleManager;

$APPLICATION->SetTitle("Корзина")

?>
<?php if (ModuleManager::isModuleInstalled('sale')) { ?>
    <? $APPLICATION->IncludeComponent(
	"bitrix:sale.basket.basket", 
	"template.1", 
	array(
		"DEFERRED_REFRESH" => "N",
		"USE_DYNAMIC_SCROLL" => "Y",
		"SHOW_FILTER" => "Y",
		"SHOW_RESTORE" => "Y",
		"ORDER_FAST_USE" => "Y",
		"ORDER_FAST_TEMPLATE" => "reserve",
		"ORDER_FAST_AJAX_MODE" => "Y",
		"COLUMNS_LIST_EXT" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "PROPS",
			3 => "DELETE",
			4 => "DELAY",
			5 => "SUM",
		),
		"COLUMNS_LIST_MOBILE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "DELETE",
			3 => "DELAY",
			4 => "SUM",
		),
		"TOTAL_BLOCK_DISPLAY" => array(
			0 => "top",
		),
		"PRICE_DISPLAY_MODE" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"DISCOUNT_PERCENT_POSITION" => "bottom-right",
		"PRODUCT_BLOCKS_ORDER" => "props,sku,columns",
		"USE_PRICE_ANIMATION" => "Y",
		"LABEL_PROP" => array(
			0 => "NEW",
			1 => "HIT",
			2 => "RECOMMEND",
		),
		"PATH_TO_ORDER" => "/personal/basket/order.php",
		"HIDE_COUPON" => "N",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"USE_PREPAYMENT" => "N",
		"QUANTITY_FLOAT" => "Y",
		"CORRECT_RATIO" => "Y",
		"AUTO_CALCULATION" => "Y",
		"SET_TITLE" => "Y",
		"ACTION_VARIABLE" => "basketAction",
		"COMPATIBLE_MODE" => "Y",
		"EMPTY_BASKET_HINT_PATH" => "/",
		"OFFERS_PROPS" => array(
		),
		"BASKET_IMAGES_SCALING" => "adaptive",
		"USE_GIFTS" => "N",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"COMPONENT_TEMPLATE" => "template.1",
		"SETTINGS_USE" => "Y",
		"QUICK_VIEW_USE" => "N",
		"TOTAL_BLOCK_FIXED_MODE" => "N",
		"ADDITIONAL_PICT_PROP_13" => "-",
		"ADDITIONAL_PICT_PROP_14" => "-",
		"QUICK_VIEW_SLIDE_USE" => "N",
		"QUICK_VIEW_TEMPLATE" => "2",
		"QUICK_VIEW_PROPERTY_CODE" => array(
			0 => "PROPERTY_TYPE",
			1 => "PROPERTY_QUANTITY_OF_STRIPS",
			2 => "PROPERTY_POWER",
			3 => "PROPERTY_PROCREATOR",
			4 => "PROPERTY_SCOPE",
			5 => "PROPERTY_DISPLAY",
			6 => "PROPERTY_WEIGTH",
			7 => "PROPERTY_ENERGY_CONSUMPTION",
			8 => "PROPERTY_SETTINGS",
			9 => "PROPERTY_COMPOSITION",
			10 => "PROPERTY_LENGTH",
			11 => "PROPERTY_SEASON",
			12 => "PROPERTY_PATTERN",
		),
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"QUICK_VIEW_IBLOCK_TYPE" => "catalogs",
		"QUICK_VIEW_IBLOCK_ID" => "13",
		"OFFERS_PROPERTY_CODE" => "",
		"OFFERS_FIELD_CODE" => "",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"BASKET_URL" => "/personal/basket.php",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"USE_PRICE_COUNT" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"CONVERT_CURRENCY" => "Y",
		"USE_COMPARE" => "Y",
		"QUICK_VIEW_PROPERTY_MARKS_HIT" => "HIT",
		"QUICK_VIEW_PROPERTY_MARKS_NEW" => "NEW",
		"QUICK_VIEW_PROPERTY_MARKS_RECOMMEND" => "RECOMMEND",
		"QUICK_VIEW_PROPERTY_PICTURES" => "PICTURES",
		"QUICK_VIEW_PROPERTY_ORDER_USE" => "",
		"QUICK_VIEW_OFFERS_PROPERTY_PICTURES" => "PICTURES",
		"QUICK_VIEW_OFFERS_PROPERTY_PICTURE_DIRECTORY" => "",
		"QUICK_VIEW_OFFERS_VARIABLE_SELECT" => "offer",
		"QUICK_VIEW_PROPERTY_TEXT" => "",
		"QUICK_VIEW_LAZYLOAD_USE" => "Y",
		"QUICK_VIEW_MARKS_SHOW" => "Y",
		"QUICK_VIEW_WEIGHT_SHOW" => "Y",
		"QUICK_VIEW_QUANTITY_SHOW" => "Y",
		"QUICK_VIEW_QUANTITY_MODE" => "number",
		"QUICK_VIEW_ADDITIONAL_PRODUCTS" => "Y",
		"QUICK_VIEW_ACTION" => "detail",
		"QUICK_VIEW_DESCRIPTION_SHOW" => "Y",
		"QUICK_VIEW_DESCRIPTION_MODE" => "preview",
		"QUICK_VIEW_GALLERY_PANEL" => "Y",
		"QUICK_VIEW_GALLERY_PREVIEW" => "Y",
		"QUICK_VIEW_INFORMATION_PAYMENT" => "Y",
		"QUICK_VIEW_PAYMENT_URL" => "",
		"QUICK_VIEW_INFORMATION_SHIPMENT" => "Y",
		"QUICK_VIEW_SHIPMENT_URL" => "",
		"QUICK_VIEW_TIMER_SHOW" => "Y",
		"QUICK_VIEW_TIMER_TIME_ZERO_HIDE" => "Y",
		"QUICK_VIEW_TIMER_MODE" => "discount",
		"QUICK_VIEW_TIMER_ELEMENT_ID_INTRODUCE" => "N",
		"QUICK_VIEW_TIMER_TIMER_SECONDS_SHOW" => "N",
		"QUICK_VIEW_TIMER_TIMER_QUANTITY_SHOW" => "Y",
		"QUICK_VIEW_TIMER_TIMER_QUANTITY_ENTER_VALUE" => "N",
		"QUICK_VIEW_TIMER_TIMER_PRODUCT_UNITS_USE" => "Y",
		"QUICK_VIEW_TIMER_TIMER_QUANTITY_HEADER_SHOW" => "Y",
		"QUICK_VIEW_TIMER_TIMER_QUANTITY_HEADER" => "Остаток",
		"QUICK_VIEW_TIMER_TIMER_HEADER_SHOW" => "Y",
		"QUICK_VIEW_TIMER_TIMER_HEADER" => "До конца акции",
		"QUICK_VIEW_TIMER_SETTINGS_USE" => "N",
		"QUICK_VIEW_TIMER_LAZYLOAD_USE" => "N",
		"QUICK_VIEW_TIMER_TIMER_QUANTITY_OVER" => "Y",
		"QUICK_VIEW_TIMER_TIMER_TITLE_SHOW" => "Y",
		"LABEL_PROP_MOBILE" => array(
			0 => "NEW",
			1 => "HIT",
			2 => "RECOMMEND",
		),
		"LABEL_PROP_POSITION" => "top-left",
		"QUICK_VIEW_TIMER_TIMER_TITLE_ENTER" => "N",
		"CURRENCY_ID" => "RUB",
		"COMPARE_PATH" => "/catalog/compare.php",
		"COMPARE_NAME" => "compare",
		"QUICK_VIEW_DELAY_USE" => "N",
		"QUICK_VIEW_MARKS_ORIENTATION" => "horizontal",
		"QUICK_VIEW_PROPERTIES_SHOW" => "N",
		"QUICK_VIEW_DETAIL_SHOW" => "N",
		"CONFIRM_REMOVE_PRODUCT_USE" => "N",
		"ORDER_FAST_VARIABLES_ACTION" => "action",
		"ORDER_FAST_VARIABLES_VALUES" => "values",
		"ORDER_FAST_CURRENCY" => "",
		"ORDER_FAST_DELIVERY" => "1",
		"ORDER_FAST_PAYMENT" => "1",
		"ORDER_FAST_PERSON" => "1",
		"ORDER_FAST_FIELDS_COMMENT_USE" => "Y",
		"ORDER_FAST_SETTINGS_USE" => "N",
		"ORDER_FAST_LAZYLOAD_USE" => "N",
		"ORDER_FAST_CONSENT_SHOW" => "Y",
		"ORDER_FAST_CONSENT_URL" => "#SITE_DIR#company/consent/",
		"ORDER_FAST_MESSAGES_TITLE" => "",
		"ORDER_FAST_MESSAGES_ORDER" => "",
		"ORDER_FAST_MESSAGES_BUTTON" => "",
		"ORDER_FAST_PROPERTY_ARTICLE" => "",
		"ORDER_FAST_OFFERS_PROPERTY_ARTICLE" => "",
		"ORDER_FAST_AJAX_OPTION_JUMP" => "N",
		"ORDER_FAST_AJAX_OPTION_STYLE" => "Y",
		"ORDER_FAST_AJAX_OPTION_HISTORY" => "N",
		"ORDER_FAST_AJAX_OPTION_ADDITIONAL" => "",
		"MIN_SUMM" => "15000",
		"QUICK_VIEW_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"QUICK_VIEW_OFFERS_SORT_FIELD" => "sort",
		"QUICK_VIEW_OFFERS_SORT_ORDER" => "asc",
		"QUICK_VIEW_OFFERS_SORT_FIELD2" => "id",
		"QUICK_VIEW_OFFERS_SORT_ORDER2" => "desc",
		"QUICK_VIEW_OFFERS_LIMIT" => "0",
		"QUICK_VIEW_PRICE_CODE" => "",
		"QUICK_VIEW_USE_PRICE_COUNT" => "N",
		"QUICK_VIEW_SHOW_PRICE_COUNT" => "1",
		"QUICK_VIEW_PRICE_VAT_INCLUDE" => "Y",
		"QUICK_VIEW_PRICE_VAT_SHOW_VALUE" => "N",
		"QUICK_VIEW_HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"QUICK_VIEW_CONVERT_CURRENCY" => "N",
		"QUICK_VIEW_CURRENCY_ID" => "RUB",
		"ADDITIONAL_PICT_PROP_43" => "-",
		"ADDITIONAL_PICT_PROP_44" => "-",
		"ADDITIONAL_PICT_PROP_46" => "-",
		"ORDER_FAST_PROPERTIES" => array(
		),
		"ADDITIONAL_PICT_PROP_50" => "-"
	),
	false
); ?>
<?php } else { ?>
    <? $APPLICATION->IncludeComponent(
        "intec:startshop.basket",
        ".default",
        array(
            "COMPONENT_TEMPLATE" => ".default",
            "CURRENCY" => "rub",
            "REQUEST_VARIABLE_ACTION" => "action",
            "REQUEST_VARIABLE_ITEM" => "item",
            "REQUEST_VARIABLE_QUANTITY" => "quantity",
            "REQUEST_VARIABLE_PAGE" => "page",
            "URL_BASKET_EMPTY" => "",
            "USE_ITEMS_PICTURES" => "Y",
            "USE_BUTTON_CLEAR" => "Y",
            "USE_BUTTON_BASKET" => "Y",
            "USE_SUM_FIELD" => "Y",
            "TITLE_BASKET" => "",
            "TITLE_ORDER" => "Оформление заказа",
            "TITLE_PAYMENT" => "Оплата",
            "URL_ORDER_CREATED" => "/personal/profile/orders/#ID#/",
            "USE_ADAPTABILITY" => "Y",
            "REQUEST_VARIABLE_PAYMENT" => "payment",
            "REQUEST_VARIABLE_VALUE_RESULT" => "result",
            "REQUEST_VARIABLE_VALUE_SUCCESS" => "success",
            "REQUEST_VARIABLE_VALUE_FAIL" => "fail",
            "URL_ORDER_CREATED_TO_USER" => "/personal/profile/",
            "AJAX_MODE" => "N",
            "USE_BUTTON_FAST_ORDER" => "N",
            "USE_BUTTON_CONTINUE_SHOPPING" => "Y",
            "URL_CATALOG" => "/catalog/",
            "VERIFY_CONSENT_TO_PROCESSING_PERSONAL_DATA" => "Y",
            "URL_RULES_OF_PERSONAL_DATA_PROCESSING" => "/company/consent/",
            "USE_FAST_ORDER" => "N"
        ),
        false
    ); ?>
<?php } ?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>