<?php if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die(); ?>
<?php

/**
 * @global CMain $APPLICATION
 */

?>
<?php $APPLICATION->IncludeComponent(
	"intec.universe:main.footer", 
	"template.1.custom", 
	array(
		"SETTINGS_USE" => "N",
		"PRODUCTS_VIEWED_SHOW" => "N",
		"PRODUCTS_VIEWED_LAZYLOAD_USE" => "N",
		"REGIONALITY_USE" => "N",
		"CONTACTS_USE" => "Y",
		"CONTACTS_IBLOCK_TYPE" => "content",
		"CONTACTS_IBLOCK_ID" => "41",
		"CONTACTS_REGIONALITY_USE" => "Y",
		"CONTACTS_REGIONALITY_STRICT" => "N",
		"MENU_MAIN_ROOT" => "bottom",
		"MENU_MAIN_CHILD" => "left",
		"MENU_MAIN_LEVEL" => "4",
		"SEARCH_NUM_CATEGORIES" => "1",
		"SEARCH_TOP_COUNT" => "5",
		"SEARCH_ORDER" => "date",
		"SEARCH_USE_LANGUAGE_GUESS" => "Y",
		"SEARCH_CHECK_DATES" => "N",
		"SEARCH_SHOW_OTHERS" => "N",
		"SEARCH_INPUT_ID" => "footer-search",
		"SEARCH_TIPS_USE" => "N",
		"SEARCH_MODE" => "site",
		"LOGOTYPE_PATH" => "/include/logotype.intec.php",
		"LOGOTYPE_LINK" => "",
		"CONTACTS_PROPERTY_CITY" => "CITY",
		"CONTACTS_PROPERTY_ADDRESS" => "ADDRESS",
		"CONTACTS_PROPERTY_PHONE" => "PHONE",
		"CONTACTS_PROPERTY_EMAIL" => "EMAIL",
		"CONTACTS_PROPERTY_REGION" => "REGIONS",
		"PHONE_VALUE" => "+7 (000) 000 00 00",
		"PRODUCTS_VIEWED_IBLOCK_MODE" => "multi",
		"ADDRESS_VALUE" => "г. Челябинск",
		"EMAIL_VALUE" => "shop@example.com",
		"COPYRIGHT_VALUE" => "&copy; #YEAR# Yoliba, Все права защищены",
		"FORMS_CALL_ID" => "1",
		"FORMS_CALL_TEMPLATE" => ".default",
		"SOCIAL_VK_LINK" => "1",
		"SOCIAL_FACEBOOK_LINK" => "",
		"SOCIAL_INSTAGRAM_LINK" => "",
		"SOCIAL_TWITTER_LINK" => "",
		"SOCIAL_YOUTUBE_LINK" => "",
		"SOCIAL_YANDEX_DZEN_LINK" => "1",
		"SOCIAL_TELEGRAM_LINK" => "1",
		"SOCIAL_TIKTOK_LINK" => "",
		"SOCIAL_SNAPCHAT_LINK" => "1",
		"SOCIAL_PINTEREST_LINK" => "",
		"SOCIAL_MAIL_RU_LINK" => "",
		"SOCIAL_WHATSAPP_LINK" => "",
		"LOGOTYPE_SHOW" => "Y",
		"PHONE_SHOW" => "Y",
		"PRODUCTS_VIEWED_TITLE_SHOW" => "Y",
		"PRODUCTS_VIEWED_TITLE" => "Ранее вы смотрели",
		"PRODUCTS_VIEWED_PAGE_ELEMENT_COUNT" => "10",
		"PRODUCTS_VIEWED_COLUMNS" => "4",
		"PRODUCTS_VIEWED_SHOW_NAVIGATION" => "Y",
		"ADDRESS_SHOW" => "Y",
		"EMAIL_SHOW" => "Y",
		"COPYRIGHT_SHOW" => "Y",
		"FORMS_CALL_SHOW" => "Y",
		"FORMS_CALL_TITLE" => "Заказать звонок",
		"MENU_MAIN_SHOW" => "Y",
		"SEARCH_SHOW" => "N",
		"SOCIAL_SHOW" => "Y",
		"THEME" => "dark",
		"TEMPLATE" => "template.6",
		"ICONS" => array(
			0 => "",
			1 => "",
		),
		"CONSENT_URL" => "/company/consent/",
		"CATALOG_URL" => "/catalog/",
		"SEARCH_URL" => "/search/",
		"PRODUCTS_VIEWED_PRICE_CODE" => array(
			0 => "BASE",
		),
		"SEARCH_CATEGORY_0" => array(
			0 => "no",
		),
		"SEARCH_PRICE_CODE" => array(
			0 => "BASE",
		),
		"SEARCH_PRICE_VAT_INCLUDE" => "Y",
		"SEARCH_CURRENCY_CONVERT" => "N",
		"COMPONENT_TEMPLATE" => "template.1.custom",
		"SECOND_PHONE_SHOW" => "N",
		"CONTACTS_ELEMENTS" => array(
			0 => "320",
			1 => "321",
			2 => "322",
			3 => "64260",
			4 => "",
		),
		"CONTACTS_ELEMENT" => "320",
		"SEARCH_PRODUCTS_SHOW" => "N",
		"SEARCH_TIPS_VIEW" => "list.1",
		"COMPANY_NAME" => "",
		"PRODUCTS_VIEWED_IBLOCK_TYPE" => "content",
		"PRODUCTS_VIEWED_IBLOCK_ID" => "",
		"SOCIAL_ODNOKLASSNIKI_LINK" => "1",
		"SOCIAL_VIBER_LINK" => "",
		"SOCIAL_LINKEDIN_LINK" => "1",
		"SOCIAL_SQUARE" => "N",
		"SOCIAL_GREY" => "Y",
		"PRODUCTS_VIEWED_CONVERT_CURRENCY" => "N",
		"PRODUCTS_VIEWED_SHOW_PRODUCTS_13" => "N",
		"PRODUCTS_VIEWED_SHOW_PRODUCTS_43" => "N",
		"SEARCH_CATEGORY_0_TITLE" => "",
		"BUTTON_SHAPE" => "square",
		"COMPANY_TIME" => "Пн-Пт: 9:30 — 18:00"
	),
	false
); ?>
